name: Test and lint SDK
on:
  pull_request:
    paths:
      - '**/*'

jobs:
  lint-test-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        with:
          path: './node_modules'
          key: ${{ runner.os }}-root-node-modules-${{ hashFiles('./yarn.lock') }}
      - name: Install SDK dependencies
        run: yarn --frozen-lockfile
        working-directory: ./
      - name: Check code with eslint
        run: npx eslint '**/*.{ts,tsx}'
        working-directory: ./
      - name: Run tests
        run: yarn test
        working-directory: ./
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        with:
          path: './node_modules'
          key: ${{ runner.os }}-root-node-modules-${{ hashFiles('./yarn.lock') }}
      - name: Install SDK dependencies
        run: yarn --frozen-lockfile
        working-directory: ./
      - name: Run typecheck
        run: yarn typecheck
        working-directory: ./