name: Test and lint SDK
on:
  pull_request:
    paths:
      - '**/*'

  workflow_dispatch:

  workflow_call:
    inputs:
      test_data_branch:
        type: string
        description: The branch in sdk-test-data to target for testcase files
        required: false
        default: main
      sdk_branch:
        type: string
        description: The branch of the SDK to test
        required: false

env:
  SDK_BRANCH_NAME: ${{ inputs.sdk_branch  || github.head_ref || github.ref_name || 'main' }}
  TEST_DATA_BRANCH_NAME: ${{ inputs.test_data_branch || 'main' }}
        
jobs:
  lint-test-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Display Testing Details
        run: |
          echo "Running SDK Test using"
          echo "Test Data: sdk-test-data@${TEST_DATA_BRANCH_NAME}"
          echo "SDK Branch: js-client-sdk@${SDK_BRANCH_NAME}"
      - uses: actions/checkout@v2
        with:
          repository: Eppo-exp/js-client-sdk
          ref: ${{ env.SDK_BRANCH_NAME }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - uses: actions/cache@v2
        with:
          path: './node_modules'
          key: ${{ runner.os }}-root-node-modules-${{ hashFiles('./yarn.lock') }}
      - name: 'Set up GCP SDK for downloading test data'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Install SDK dependencies
        run: yarn --frozen-lockfile
        working-directory: ./
      - name: Check code with eslint
        run: npx eslint '**/*.{ts,tsx}'
        working-directory: ./
      - name: Run tests
        run: make test branchName=${{ env.TEST_DATA_BRANCH_NAME }}
        working-directory: ./
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Eppo-exp/js-client-sdk
          ref: ${{ env.SDK_BRANCH_NAME }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - uses: actions/cache@v2
        with:
          path: './node_modules'
          key: ${{ runner.os }}-root-node-modules-${{ hashFiles('./yarn.lock') }}
      - name: Install SDK dependencies
        run: yarn --frozen-lockfile
        working-directory: ./
      - name: Run typecheck
        run: yarn typecheck
        working-directory: ./
