name: Test and lint SDK
on:
  pull_request:
    paths:
      - '**/*'

  workflow_dispatch:

  workflow_call:
    inputs:
      test_data_branch:
        type: string
        description: The branch in sdk-test-data to target for testcase files
        required: false
        default: main
      sdk_branch:
        type: string
        description: The branch of the SDK to test
        required: false

env:
  SDK_BRANCH_NAME: ${{ inputs.sdk_branch  || github.head_ref || github.ref_name || 'main' }}
  TEST_DATA_BRANCH_NAME: ${{ inputs.test_data_branch || 'main' }}

jobs:
  lint-test-sdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '18', '20', '22', '23' ]
    steps:
      - name: Display Testing Details
        run: |
          echo "Running SDK Test using"
          echo "Test Data: sdk-test-data@${TEST_DATA_BRANCH_NAME}"
          echo "SDK Branch: js-client-sdk@${SDK_BRANCH_NAME}"
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install SDK dependencies
        run: yarn --frozen-lockfile
        working-directory: ./
      - name: Check code with eslint
        run: npx eslint '**/*.{ts,tsx}'
        working-directory: ./
      - name: Run tests
        run: make test branchName=${{ env.TEST_DATA_BRANCH_NAME }}
        working-directory: ./
  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '18', '20', '22', '23' ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install SDK dependencies
        run: yarn --frozen-lockfile
        working-directory: ./
      - name: Run typecheck
        run: yarn typecheck
        working-directory: ./
